#!/bin/bash

# chunkc core::load ffm.so
chunkc core::log_file stdout
chunkc core::log_level warn
chunkc core::plugin_dir /usr/local/opt/chunkwm/share/chunkwm/plugins
chunkc core::hotload 0

chunkc set custom_bar_enabled            0
chunkc set custom_bar_all_monitors       1
chunkc set custom_bar_offset_top         22
chunkc set custom_bar_offset_bottom      0
chunkc set custom_bar_offset_left        0
chunkc set custom_bar_offset_right       0

chunkc set global_desktop_mode           bsp
chunkc set global_desktop_offset_top     00
chunkc set global_desktop_offset_bottom  00
chunkc set global_desktop_offset_left    00
chunkc set global_desktop_offset_right   00
chunkc set global_desktop_offset_gap     vz0

#
# NOTE: syntax for desktop-specific settings
#
# chunkc set 2_desktop_mode                monocle
# chunkc set 5_desktop_mode                float
# chunkc set 3_desktop_offset_top          190
# chunkc set 3_desktop_offset_bottom       190
# chunkc set 3_desktop_offset_left         190
# chunkc set 3_desktop_offset_right        190
# chunkc set 3_desktop_offset_gap          30
#

chunkc set desktop_padding_step_size     10.0
chunkc set desktop_gap_step_size         5.0

chunkc set bsp_spawn_left                1
chunkc set bsp_optimal_ratio             1.618
chunkc set bsp_split_mode                optimal
chunkc set bsp_split_ratio               0.5

chunkc set monitor_focus_cycle           1
chunkc set window_focus_cycle            monitor

chunkc set mouse_follows_focus           intrinsic
chunkc set window_float_next             0
chunkc set window_region_locked          1

chunkc set preselect_border_color        0xffd75f5f
chunkc set preselect_border_width        10
chunkc set preselect_border_radius       0
chunkc set preselect_border_outline      0

chunkc set window_float_topmost          0
chunkc set window_fade_inactive          0
chunkc set window_fade_alpha             0.85
chunkc set window_fade_duration          0.25
chunkc set window_use_cgs_move           0

#
# NOTE: the following are config variables for the chunkwm-border plugin.
#
# NOTE: syntax for `focused_border_outline` setting
#       0 = false, inline border
#       1 = true, outline border
#

chunkc set focused_border_color          0x000000
chunkc set focused_border_width          50
chunkc set focused_border_radius         0
chunkc set focused_border_outline        1
chunkc set focused_border_skip_floating  0
chunkc set focused_border_skip_monocle   0

#
# NOTE: specify plugins to load when chunkwm starts.
#

chunkc core::unload border.so
chunkc core::load tiling.so

chunkc tiling::rule --owner Finder --name Copy --state float &
chunkc tiling::rule --owner \"App Store\" --state float &
chunkc tiling::rule --name \"Microsoft Excel\" --state float &
chunkc tiling::rule --owner \"IntelliJ IDEA\" --name Evaluate --state float &
chunkc tiling::rule --owner Spotify --state float &
chunkc tiling::rule --owner Emacs --except "^$" --state tile &

