#!/usr/bin/env sh

# global settings
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          off
yabai -m config window_placement             second_child
yabai -m config window_topmost               on
#yabai -m config active_window_border_topmost on
yabai -m config window_shadow                off
yabai -m config window_opacity               off
yabai -m config window_opacity_duration      0.0
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        1.0
yabai -m config window_border                off
#yabai -m config window_border_width          0.5
yabai -m config active_window_border_color   0x66d7fa37
yabai -m config normal_window_border_color   0xff555555
yabai -m config insert_feedback_color        0xffd75f5f
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               ctrl
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  10
yabai -m config bottom_padding               10
yabai -m config left_padding                 10
yabai -m config right_padding                10
yabai -m config window_gap                   10

#yabai -m signal --add event=window_created app="${apps}" action='~/.local/bin/yabai-float-children'
yabai -m rule --add app="^Tor Browser$" manage=off
yabai -m rule --add app="^DB Solo 5$" manage=off
yabai -m rule --add app="^IntegrationStudio$" manage=off
yabai -m rule --add app="^Emacs$" manage=on
yabai -m rule --add app="^Slash$" manage=off
yabai -m rule --add app="^IntelliJ IDEA$" border=off
yabai -m rule --add app="^Sublime Merge$" border=off
yabai -m rule --add app="^Spotify$" border=off
yabai -m rule --add app="^Calendar$" manage=off
yabai -m rule --add app="^Finder$" manage=off
yabai -m rule --add app="^Due$" manage=off
yabai -m rule --add app="^main$" manage=off
yabai -m rule --add app="^Toggl Track$" manage=off
