#! /bin/sh

# dbus fix
# systemctl --user import-environment DISPLAY
# gtk cursor & scaling
xrdb -merge ~/.Xresources
# gets rid of X cursor
xsetroot -cursor_name left_ptr
# layout
setxkbmap us,ua -variant dvorak, -option grp:win_space_toggle
# key repeat
xset r rate 250 50

# transparency
pidof picom || { picom & }

# hotkeys (reload themselves)
pidof sxhkd || { sxhkd & }

# menu
pkill polybar
polybar main &

# wallpaper
pkill feh
feh --no-fehbg --bg-scale ".background" &

# . "${HOME}/.cache/wal/colors.sh"

##########
# CONFIG #
##########

# workspaces
bspc monitor -d 1 2 3 4 5 6

bspc config border_width          10
bspc config normal_border_color   "$color1"
bspc config focused_border_color  "$color3"
bspc config active_border_color   "$color4"
bspc config presel_feedback_color "$color2"
bspc config window_gap            50
bspc config top_padding           70
bspc config bottom_padding        0

bspc config normal_frame_opacity  0.55
bspc config focused_frame_opacity 0.55

bspc config split_ratio           0.5
bspc config borderless_monocle    true
bspc config gapless_monocle       true

#########
# RULES #
#########

bspc rule -a Pcmanfm "state=floating"

