#! /bin/sh

###########
# STARTUP #
###########

# wallpaper
feh --no-fehbg --bg-center https://thisartworkdoesnotexist.com/
# compositor
picom &
# notifications
dunst &
# gtk cursor & scaling
xrdb ~/.Xresources
# gets rid of X cursor
xsetroot -cursor_name left_ptr
# layout
setxkbmap -layout dvorak,ru -option grp:win_space_toggle
# key repeat
xset r rate 250 50
# hotkeys
pidof sxhkd || { sxhkd & }
# menu
killall -q polybar
while pgrep -u $UID -x polybar >/dev/null; do sleep 1; done
polybar main &
# todo check for already running process
alacritty --class dropdown -e "bash -i" &

##########
# CONFIG #
##########

# workspaces
bspc monitor -d 1 2 3 4 5 6

bspc config border_width         4
bspc config normal_border_color  '#424242'
bspc config focused_border_color '#7cb342'
# cyan
# '#00BCD4'
bspc config window_gap           10
bspc config top_padding          60
bspc config bottom_padding       0

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#########
# RULES #
#########

bspc rule -a Pcmanfm "state=floating"
bspc rule -a dropdown sticky=on state=floating hidden=on

