#! /bin/sh

# gtk cursor & scaling
xrdb -merge ~/.Xresources
# gets rid of X cursor
xsetroot -cursor_name left_ptr
# layout
setxkbmap us,ua -variant dvorak, -option grp:win_space_toggle
# key repeat
xset r rate 250 50
# screen saver
#xset s `echo "60*30" | bc`
#xautolock -exit && xautolock -time 15 -locker xtrlock &

# transparency
pidof picom || { picom & }

# notifications
# dunst &

# hotkeys (reload themselves)
pidof sxhkd || { sxhkd & }

# menu
pkill polybar
polybar main &

pkill feh
feh --no-fehbg --bg-scale '.background' &

# . "${HOME}/.cache/wal/colors.sh"

##########
# CONFIG #
##########

# workspaces
bspc monitor -d 1 2 3 4 5 6

bspc config border_width          10
bspc config normal_border_color   "$color1"
bspc config focused_border_color  "$color3"
bspc config active_border_color   "$color4"
bspc config presel_feedback_color "$color2"
bspc config window_gap            50
bspc config top_padding           70
bspc config bottom_padding        0

bspc config normal_frame_opacity  0.55
bspc config focused_frame_opacity 0.55

bspc config split_ratio           0.5
bspc config borderless_monocle    true
bspc config gapless_monocle       true

#########
# RULES #
#########

bspc rule -a Pcmanfm "state=floating"
bspc rule -a "I.C.A.R.U.S." "state=floating"

#bspc config external_rules_command ~/.config/bspwm/floating_desktop.sh

